### ISSUE TITLE
Compilation error: 'make_unique' is not a member of 'std'

### ISSUE THREAD

**Issue by jinQQQQQ** [Open-Agriculture/AgIsoStack-Arduino#7] opened 2023-12-02 07:46 UTC
I don't have this board and try to port it to EPS32s3, 
But there was an error. The compiler does not support C++14. I tried to modify it, but it failed. I hope that the code can be backward compatible to C++11
Arduino IDE 2.2.1
![image](https://github.com/Open-Agriculture/AgIsoStack-Arduino/assets/46147928/85a6dca0-e8d4-456e-9977-59808c8006ff)

`.\src\can_internal_control_function.cpp: In static member function 'static std::shared_ptr<isobus::InternalControlFunction> isobus::InternalControlFunction::create(isobus::NAME, uint8_t, uint8_t)':
.\src\can_internal_control_function.cpp:32:46: error: 'make_unique' is not a member of 'std'
   controlFunction->pgnRequestProtocol = std::make_unique<ParameterGroupNumberRequestProtocol>(controlFunction, badge);
                                              ^~~~~~~~~~~
.\src\can_internal_control_function.cpp:32:46: note: 'std::make_unique' is only available from C++14 onwards

.\src\can_hardware_interface_single_thread.cpp:42:36: error: 'make_unique' is not a member of 'std'
    hardwareChannels.push_back(std::make_unique<CANHardware>());
`

**Comment by GwnDaan** [comment] 2024-02-20 17:20
Should be fixed with https://github.com/Open-Agriculture/AgIsoStack-Arduino/pull/8. Feel free to re-open the issue if the issue is still present

**Closed by GwnDaan** 2024-02-20 17:20 UTC
